[package]
name = "rune"
version = "0.1.0"
authors = ["Sushant <sushant.dinesh94@gmail.com>"]

[dependencies]
petgraph = "*"
rustc-serialize = "*"

[dependencies.radeco-lib]
path = "../radeco-lib/"

[dependencies.esil]
path = "../esil-rs/"

[dependencies.r2pipe]
path = "../r2pipe.rs/"
